### ISSUE TITLE
Непотрібний upload_tender_document

### ISSUE THREAD

**Issue by leits** [openprocurement/openprocurement.client.python#12]
Зайвий метод upload_tender_document, який використовувася yankee7 для тестування.

https://github.com/openprocurement/openprocurement.client.python/blob/a1b19f128ca851c24e49e68c60bed154d86d3e5e/openprocurement_client/client.py#L316

**Comment by selurvedu** [comment]
Вирішено в https://github.com/openprocurement/openprocurement.client.python/commit/67951dbb76893c0ebde212976fc59e22674eb198 .
