### ISSUE TITLE
Оновлення документу

### ISSUE THREAD

**Issue by leits** [openprocurement/openprocurement.client.python#13]
Існував update_document, який видалили. Чому і чи не потребує він відновлення?

https://github.com/openprocurement/openprocurement.client.python/commit/c7ce22cdbaa9d5d1767bb4c345bd58ea12a1a95f#diff-b97282a5911a3be9bf7bc97abe31abe8L199

**Comment by selurvedu** [comment]
Цей метод використовувався лише в `robot_tests`. Коли розробка `robot_tests` лише почалась, можна було створювати файл в пам’яті, і відразу додавати його до POST'у, не записуючи на диск і не зчитуючи звідти. Потім до референсної імплементації (`openprocurement_client.robot`) додались інші брокери, які працюють через GUI (сайт в браузері або окремий софт), і їм потрібен був реальний файл на диску, який можна вибрати в file chooser'і. Цей метод все ще спрацює для `openprocurement_client.robot`, але не для інших брокерів.
