### ISSUE TITLE
Тестовий update_bid_document

### ISSUE THREAD

**Issue by leits** [openprocurement/openprocurement.client.python#14]
Створює файл з переданим ім’ям, записуєю у нього 'fixed text data' і заміняє ним існуючий. А має отримувати файл і ним заміняти існуючий.

https://github.com/openprocurement/openprocurement.client.python/blob/a1b19f128ca851c24e49e68c60bed154d86d3e5e/openprocurement_client/client.py#L336

**Comment by selurvedu** [comment]
Вирішено в https://github.com/openprocurement/openprocurement.client.python/commit/fb6f79e592410d40457c8b0a98fbd93117b8b9f7 . Отримувати наявний файл не треба, можна відразу давати новий "не дивлячись".
