### ISSUE TITLE
Видалення пропозиції і лоту

### ISSUE THREAD

**Issue by leits** [openprocurement/openprocurement.client.python#15]
Зараз для видалення пропозиції у функцію delete_bid передається увесь bid, після чого вичитується його id i token. Можна зробити за принципом get_bid, передаючи одразу bid_id i access_token замість усього файлу.
https://github.com/openprocurement/openprocurement.client.python/blob/a1b19f128ca851c24e49e68c60bed154d86d3e5e/openprocurement_client/client.py#L365

Для delete_lot можна ж передавати лише lot_id, адже token береться з тендеру.
https://github.com/openprocurement/openprocurement.client.python/blob/a1b19f128ca851c24e49e68c60bed154d86d3e5e/openprocurement_client/client.py#L375

**Comment by selurvedu** [comment]
В майбутньому давай лінк на конкретну ревізію (в цьому випадку `/blob/a1b19f128ca851c24e49e68c60bed154d86d3e5e`), бо master завжди встигне втекти вперед, і лінки будуть вказувати не туди, куди мали б. Підправив опис.
